[tool.poetry]
name = "homesite"
version = "0.1.0"
description = "Homesite for Family"
authors = ["Maxim Britvin <maksbritvin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = "^0.23.2"
duckdb = "^0.9.1"
ruff = "^0.1.3"
mypy = "^1.6.1"
pytest = "^7.4.3"
sqlalchemy = "^2.0.22"
psycopg2 = "^2.9.9"
python-dotenv = "^1.0.0"
pydantic-settings = "^2.0.3"

[tool.ruff]
line-length = 120
src = ["src"]
select = [
  "E", # pycodestyle
  "F", # pyflakes
  "UP", # pyupgrade
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
