# Generated by Django 5.0 on 2024-01-17 08:18

from django.db import migrations
import datetime

def init_periods(apps, schema_editor):
    Period = apps.get_model("budget", "Period")
    period_jan = Period(
        name="Январь-2024", 
        start_date=datetime.date(2024,1,1),
        end_date=datetime.date(2024,1,31),
        year=2024,
        month=1,
        short_name="Янв-2024"
    )
    period_jan.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_periods)
    ]
