# Generated by Django 5.0 on 2023-12-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.CharField(max_length=250, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.category')),
            ],
        ),
    ]
