# Generated by Django 5.0 on 2023-12-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_remove_operation_account_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalisationDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='detalisation',
            field=models.JSONField(null=True),
        ),
        migrations.CreateModel(
            name='DetalisationDimensionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField(default=-1)),
                ('dim_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget.detalisationdimension')),
            ],
        ),
    ]
