# Generated by Django 5.0 on 2023-12-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_detalisationdimension_operation_detalisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
