# Generated by Django 5.0 on 2024-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('Dr', 'Доход'), ('Cr', 'Расход')], default='Cr', max_length=2),
        ),
    ]
