# Generated by Django 5.0 on 2024-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_category_cat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_period',
            field=models.CharField(default='Test 2023', max_length=30),
            preserve_default=False,
        ),
    ]
