# Generated by Django 5.0 on 2024-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_operation_operation_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='detalisation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
