# Generated by Django 5.0 on 2024-01-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_operation_comment_alter_operation_detalisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('short_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operation_period',
        ),
    ]
