# Generated by Django 5.0 on 2024-01-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_period_remove_operation_operation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget.period'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
    ]
