# Generated by Django 5.0 on 2024-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_operation_operation_period_alter_operation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='month',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
