# Generated by Django 5.0 on 2023-12-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_date',
            field=models.DateField(),
        ),
    ]
