# Generated by Django 5.0 on 2024-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_period_month_period_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
